### ISSUE TITLE
Cannot properly parse XML files

### ISSUE THREAD

**Issue by rubek** [wolfgangmuender/InspectorTodo#3]
TODO comments in XML files skips digits. To reproduce:

* Add a TODO comment in some XML file, e.g. `<!-- TODO PRO-1234 Do something -->`
* Run Inspector Todo
* Inspector Todo  reads `<!-- TODO PRO-34 Do something -->` and fails as that ticket is pretty old and Done already.

**Comment by wolfgangmuender** [comment]
Could not exactly reproduce the issue, maybe due to the changes in bd11d83. Added test in addd2a8 and fixed minor bug.
