### ISSUE TITLE
Support Vue JS files

### ISSUE THREAD

**Issue by hvennekate** [wolfgangmuender/InspectorTodo#4]
See (for reference and as a starting point): https://vuejs.org/v2/guide/single-file-components.html
Note: These may contain both XML comments `<!-- comment -->`, as well as JavaScript comments of the `// comment`-kind (and, technically also `/* ... */`, but I guess for the purpose of TODOs, these can be neglected).

**Comment by wolfgangmuender** [comment]
Closed via 1ecc6d56c1f99ee2e22f2fe49b555d2e85821d92.
